---
# defaults file for kpsinghchouhan.linux_system_roles.swap

# Variable that will be displayed in debug output
# This demonstrates proper role variable naming with the 'run_' prefix
swap_enable: false
swap_file_path: /swap.img
swap_file_size: 1.9G
