---
# argument spec file for kpsinghchouhan.linux_system_roles.swap

argument_specs:
  main:
    short_description: Role description.
    options:
      swap_my_variable:
        type: str
        description: A simple string argument for demonstration.
        default: "default_value"
